call bundle_1_brick_1.bat
call bundle_1_brick_2.bat
call bundle_1_brick_3.bat
call bundle_1_brick_4.bat
call bundle_1_brick_5.bat
call bundle_1_brick_6.bat
call bundle_1_brick_7.bat
call bundle_1_brick_8.bat
call bundle_1_brick_9.bat
call bundle_1_brick_10.bat
call bundle_1_brick_11.bat
call bundle_1_brick_12.bat